// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatinhasQueBrilham.Repository;

namespace PatinhasQueBrilham.Migrations
{
    [DbContext(typeof(PatinhasContext))]
    [Migration("20190220173014_AlteracaoReserva")]
    partial class AlteracaoReserva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatinhasQueBrilham.Models.Reserva", b =>
                {
                    b.Property<int>("reservaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("celular")
                        .IsRequired();

                    b.Property<string>("comentario");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("fromDate")
                        .IsRequired();

                    b.Property<string>("nomeDono")
                        .IsRequired();

                    b.Property<string>("nomePet")
                        .IsRequired();

                    b.Property<string>("raca");

                    b.Property<string>("residencial");

                    b.Property<int>("ticket");

                    b.Property<string>("tipoPet");

                    b.Property<string>("toDate");

                    b.HasKey("reservaId");

                    b.ToTable("reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
